M48
; DRILL file {KiCad 6.0.7-1.fc36} date Thu Aug 25 14:46:05 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-25T14:46:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-1.fc36
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.170
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.450
%
G90
G05
T1
X80.4Y-154.64
T2
X54.986Y-151.561
X61.863Y-156.027
T3
X101.505Y-149.82
T4
X84.0Y-86.4
X84.0Y-141.6
T5
X66.495Y-141.6
X101.505Y-86.4
T1
X87.45Y-154.64G85X87.75Y-154.64
G05
T0
M30
